framework:
    messenger:

        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: session.action.bus
        buses:
            session.action.bus:
                middleware:
#                     - handle_message
                default_middleware: allow_no_handlers
                
            session.event.bus:
                middleware:
#                     - handle_message
                default_middleware: allow_no_handlers
                
            environment.action.bus:
                middleware:
#                     - handle_message
                default_middleware: allow_no_handlers
                
            environment.event.bus:
                middleware:
#                     - handle_message
                default_middleware: allow_no_handlers

            awx.action.bus:
                middleware:
                default_middleware: allow_no_handlers
            
            awx.event.bus:
                middleware:
#                     - handle_message
#                    - validation
#                    - doctrine_transaction
                # the 'allow_no_handlers' middleware allows to have no handler
                # configured for this bus without throwing an exception
                default_middleware: allow_no_handlers

            lxc.operation.bus:
                middleware:
                default_middleware: allow_no_handlers

            lxc.event.bus:
                middleware:
                default_middleware: allow_no_handlers

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\Message\LxcOperation: async            # Route your messages to the transports
            App\Message\LxcEvent: async
            App\Message\AwxAction: async
            App\Message\AwxEvent: async
            App\Message\SessionAction: async
            App\Message\SessionEvent: async
            App\Message\EnvironmentAction: async
            App\Message\EnvironmentEvent: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
